name: Merge Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Merge into main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff origin/dev -m "Merge from dev to main"
          git push origin main
